<div class="grid-x">
    <div class="large-12 medium-12 small-12 columns">
        <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
            <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            <div class="title-bar-title">Menu</div>
        </div>

        <div class="top-bar" id="example-menu">
            <div class="top-bar-left">
                <ul class="dropdown menu " data-dropdown-menu>

                    <li>
                        <a href="<?php echo App::config("url")."index" ?>">Category</a>
                         <ul class="menu">
                            <li>
                                <a href="<?php echo App::config("url")."phone/index" ?>">Phones</a>
                            </li>
                            <li>
                                <a href="<?php echo App::config("url")."laptop/index" ?>">Laptops</a>
                            </li>
                            <li>
                                <a href="<?php echo App::config("url")."monitor/index" ?>">Monitors</a>
                            </li>     
                         </ul>   
                    </li>
                    <div class="top-bar-right">
                    <li>
                        <a class="top-bar-right" href="<?php echo App::config("url")."cart" ?>"><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i></a>
                            
                        </div>
                </ul>
            </div>
        </div>
    </div>
</div>

