<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once "head.phtml" ?>
    <?php echo $head ?>
  </head>
  <body>
    <div class="grid-container">

    <div class="grid-x">
        <div class="large-6 medium-6 small-6 columns">
            <h1 style="width: 100%; text-align: center; padding-top:15px;"><?php echo App::config("nazivApp") ?></h1>
        </div>
    </div>

    <?php include_once "izbornik.phtml" ?>
       
        <div class="callout" style="min-height: 400px;">
            <?php echo $content ?>
           
        </div>
       
        <div class="callout">
           &copy; <a class="git" href="https://github.com/robertzita">Robert Zita</a> <?php echo date("Y") ?>
        </div>




    </div>
    
    <script src="<?php echo App::config("url") ?>public/js/vendor/jquery.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/what-input.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/app.js"></script>
    <?php echo $js ?>
  </body>
</html>