<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th >Price</th>
            <th >Quantity</th>
            <th >Add to cart</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($phones as $phone): ?>
        <tr>
            <td><?php echo $phone->name ?></td>
            <td><?php echo $phone->description ?></td>
            <td><?php echo $phone->price ?> $</td>
            <td width="80">
                <input type="number" value="0">
            </td>
            <td>
                <input type="submit" value="Add to Cart" class="button">
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
